def ccrt_text(case_code):
    match case_code:
        case 1:
            return f"昏厥或尖叫"
        case 2:
            return f"驚慌失措地逃跑"
        case 3:
            return f"歇斯底里或情緒爆發(狂笑、哭泣等等)"
        case 4:
            return f"發出嬰兒般的咿呀聲，說話無條理、速語症、多語症"
        case 5:
            return f"強烈恐懼症，可能會定在當場不能動彈"
        case 6:
            return f"殺人傾向或自殺傾向"
        case 7:
            return f"出現幻覺或妄想症"
        case 8:
            return f"不自覺地模仿旁人的動作"
        case 9:
            return f"奇怪的食欲(泥土、黏土、人肉)"
        case 10:
            return f"恍惚(像胎兒一樣蜷縮起來，忘記一切)或緊張型精神分裂(對一切失去興趣，必須有別人引導，否則無法進行任何獨立行動)"
        case _:
            return None

def ccsu_text(case_code):
    match case_code:
        case 1:
            return f"記憶缺失、健忘(症)或恍惚/緊張症"
        case 2:
            return f"嚴重的恐懼症(可能逃跑，或將所有東西都看成害怕的東西)"
        case 3:
            return f"幻覺"
        case 4:
            return f"奇怪的性取向(裸露癖、女子淫狂/男子淫狂等)"
        case 5:
            return f"找到了某樣「幸運符」(把某樣飾品、器物甚至某人當作安全毯)，如果遠離就會一事無成"
        case 6:
            return f"無法控制地抽搐、顫抖，無法藉由語言或書寫交談"
        case 7:
            return f"精神性的失明、失聰，或某個肢體無法使用"
        case 8:
            return f"反應性精神障礙(語無倫次、幻覺、妄想症或行為異常)"
        case 9:
            return f"暫時的偏執狂"
        case 10:
            return f"強迫症(不停洗手、祈禱，以特定節奏走路，不願走在某些路面上，總是檢查子彈是否上膛等等)"
        case _:
            return None